/*
*	Usage:
*		Make sure you update the LONG_TOKEN with a value generated by nextLong().
*		Then build the program and run it. You will be given the raw seed on success.
*
*	Build with: gcc -Wall -Wpedantic -o crack-nextLong crack-nextLong.c
*/


#include <stdio.h>

/* THE nextLong TOKEN  GOES HERE vvv */
#define LONG_TOKEN -3876303079732769403 // (example token) <<<< PLACE YOUR TOKEN HERE 
#define BRUTE_N_BITS 20 // must be at least 16 (shouldn't require to be changed)

/* Returns next random 32 bit integer. */
unsigned long nextInt(unsigned long long seed) {
	return (((seed * 0x5DEECE66D + 0xB) & 0xFFFFFFFFFFFF) >> 16);
}


/*
*  This program brute forces a few more bits than should be necessary
*  just to be sure :)
*/
int main(void) {
	printf("Starting application..\n\n");

	
	unsigned long long token = LONG_TOKEN;
	unsigned long upper = token >> (32+(BRUTE_N_BITS-16));
	unsigned long lower = token & 0xFFFFFFFF;

	for (unsigned int i = 0; i<(1<<BRUTE_N_BITS); i++) {
		unsigned long long seed = (upper << BRUTE_N_BITS) + i;
		printf("[>] Trying seed: %llu\r",seed);
		if (nextInt(seed) == lower) {
			printf("\n[>] >>> SEED WAS VALID! <<<\n");
			printf("[>] Remember to reverse the seed before using it with Random(...)!");
			return 0;
		}
	}
	printf("\n[>] Exhausted! (Maybe increase the range of bits to brute force...)\n");
	return 1;
}
